---
label: Layout Select
hide_body: false
is_partial: false
fields:
- type: select
  config:
    source:
      type: simple
    required: true
    options:
    - Home
    - Blog Home
    - Projects Home
    - About
  label: Layout
  name: layout
  default: Home
